PR - oppdatere readme
NVE/Designsystem pull request #11
Opened 2023-11-22 16:53 UTC by joergenlampe

oppdatert dokumentasjon. Må oppdateres en gang til når alt er på plass.

2023-11-23 12:32 UTC, gruble requested changes
En bra start dette

2023-11-24 10:11 UTC, amish1188 commented
har oppdatert docs litt. dokumenten skal sikkert utvides i tiden. hvis dere syns det mangler noe, bare hent branchen og legg til det som trengs

2023-11-24 15:38 UTC, gruble approved these changes
Bra. Ble mye bedre nå. Jeg har et par småkommentarer, bare.
Vi kommer til å trenge mer dokumentasjon på hvordan vi utvikler komponenter, og hvilke krav som gjelder, men det kan vi ta etterhvert.

2023-11-24 15:38 UTC, gruble commented on README.md
> +# NVE Designsystem
bra

2023-11-24 15:38 UTC, gruble commented on README.md
> +[Lenke til npm-pakke.](https://www.npmjs.com/package/nve-designsystem)
NPM-linken kan du flytte til under "Skal du bruke NVE designsystem...". Fint med en forklaring på hva linken er til.

2023-11-24 15:38 UTC, gruble commented on README.md
> +```
\```js

2023-11-24 15:38 UTC, gruble commented on README.md
> +```
\```html

2023-11-24 15:38 UTC, gruble commented on README.md
> +### **kjøremiljø**
Dette er det viktigste avsnittet og kan med fordel stå først under "Skal du utvikle..."
Hadde det vært bedre å bruke overskriften "utvikling" eller "test"?

2023-11-24 15:38 UTC, gruble commented on README.md
> +### **npm**
Dette avsnittet synes jeg bør være sist, siden det er noe vi gjør sjeldent og det er kanskje få personer som skal gjøre det

2023-11-27 11:23 UTC, merged