added alert
NVE/Designsystem pull request #15
Opened 2023-11-28 11:33 UTC by amish1188

Måtte bruke previeHead i main.ts i storybook konfigurasjon for å kunne laste material-symbols, ellers funka de ikke. PreviewHead overskrevet default import av filer fra index.html derfor måtte jeg legge til alt manuelt. Hvis det finnes en bedre løsning gjerne si fra @joergenlampe . 
Lagde nye props i nve-alert som text og title og klarte å injekte tekst gjennom css content property (litt hokus pokus men fungerer fint).

2023-12-13 13:46 UTC, knutnve requested changes
**Kommentar**:

Vestre-Ikon er ikke likt selv om det er material symbols?
Close icon er ikke likt. Shoelace ikon?
Forskjellig høyde. Men det styres vel av innholdet + 16px padding?
Bodyteksten oppleves som fetere i kode enn design

![alert comment](https://github.com/NVE/Designsystem/assets/129265201/de6cea58-6b09-43c1-a167-50ef9072bc4a)

2023-12-18 12:00 UTC, knutnve commented
Liten hover feil her

https://github.com/NVE/Designsystem/assets/129265201/d692fd9b-a47e-417d-8ce7-fd1c5b2a3bc9

2023-12-18 12:06 UTC, knutnve commented
@amish1188 Er storybook den siste gjeldene? Virker som når jeg kjører feature/avn-228/nve-alert lokalt er det ikke helt oppdatert

2023-12-18 12:08 UTC, knutnve commented
- Vi har ikke varianten primary i settet våres. 


<img width="1463" alt="Screenshot 2023-12-18 at 13 07 18" src="https://github.com/NVE/Designsystem/assets/129265201/c9fcf439-ca04-44d6-8bbc-d381cb59553a">


- Neutral har egen tokens farger. Se skisser.

2023-12-19 10:47 UTC, amish1188 commented
> * Vi har ikke varianten primary i settet våres.
> 
> <img alt="Screenshot 2023-12-18 at 13 07 18" width="1463" src="https://private-user-images.githubusercontent.com/129265201/291274062-c9fcf439-ca04-44d6-8bbc-d381cb59553a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODEyOTksIm5iZiI6MTcwMjk4MDk5OSwicGF0aCI6Ii8xMjkyNjUyMDEvMjkxMjc0MDYyLWM5ZmNmNDM5LWNhMDQtNDRkNi04YmJjLWQzODFjYjU5NTUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMDE2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDJlNDg2ZmYzN2ZmMTI2ZDc5OTdlZGYwNWRkZTY0ZGY5YzgzYTQ1M2QzYjRiMTdmYWNlOTM1ZDExNzY4ZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sr4OvuFHYGF-ezy3WKVa8IzSPtjQGef5Bw8tyB-O5lA">
> * Neutral har egen tokens farger. Se skisser.

info alert i shoelace er av variant primary, så alle css klasser som vi overskrevet heter alert-primary også selve variant som skal brukes i html skal hete akkurat det samme. dette kan vi ikke overskrive (vi kunne men det er masse jobb som kanskje ikke er verdt det). kan vi ikke bare justere ds vårt så at den bruker samme navngivning på alert variantene som shoelace?

2023-12-19 11:37 UTC, knutnve commented
> > * Vi har ikke varianten primary i settet våres.
> > 
> > <img alt="Screenshot 2023-12-18 at 13 07 18" width="1463" src="https://private-user-images.githubusercontent.com/129265201/291274062-c9fcf439-ca04-44d6-8bbc-d381cb59553a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODEyOTksIm5iZiI6MTcwMjk4MDk5OSwicGF0aCI6Ii8xMjkyNjUyMDEvMjkxMjc0MDYyLWM5ZmNmNDM5LWNhMDQtNDRkNi04YmJjLWQzODFjYjU5NTUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxMDE2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDJlNDg2ZmYzN2ZmMTI2ZDc5OTdlZGYwNWRkZTY0ZGY5YzgzYTQ1M2QzYjRiMTdmYWNlOTM1ZDExNzY4ZjhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sr4OvuFHYGF-ezy3WKVa8IzSPtjQGef5Bw8tyB-O5lA">
> > * Neutral har egen tokens farger. Se skisser.
> 
> info alert i shoelace er av variant primary, så alle css klasser som vi overskrevet heter alert-primary også selve variant som skal brukes i html skal hete akkurat det samme. dette kan vi ikke overskrive (vi kunne men det er masse jobb som kanskje ikke er verdt det). kan vi ikke bare justere ds vårt så at den bruker samme navngivning på alert variantene som shoelace?

Ja det kan vi. Hva om Neutral fargen blir primary da?

2023-12-21 10:55 UTC, knutnve approved these changes
Ser bra ut. Bra jobba. 👍

2023-12-21 11:10 UTC, Citaborg approved these changes

2024-01-01 17:54 UTC, merged