PR: NveDetails - komponent (Accordion)
NVE/Designsystem pull request #155
Opened 2024-04-12 12:08 UTC by tomapedersen

Laget en Accordion-component fra designsystemet.
Arver fra SlDetails, men måtte skrive om en del for å få den til å passe med DS

(!): Min første komponent, så sjekk den ekstra nøye :)

2024-04-16 05:33 UTC, tomapedersen commented
La til "subtle"-variant som er en litt lyserer gråfarge enn "neutral". Figma hadde en ekstra farge

2024-04-16 08:09 UTC, amish1188 commented
Ser bra ut, men jeg er ikke sikker hvorfor du trenger å rendere kopiert shoelace komponent? Ikoner som shoelace komponenter bruker er allerede satt opp i registerIcons/systemLibraryCustomization.ts. De er Outlined da fordi fra det vi skjønte fra Knut Outlined skal være default. For nå så har også applikasjoner som bruker outlined ikoner ingen mulighet til å endre til Outlined i nve-details. Hvis vi trenger å ha Sharp ikoner i shoelace komponeter (noe som gir mening siden vi kan nå velge mellom outlined og sharp i selve nve-icon) så er det bare å legge en fil til i registerIcons med sharp ikoner. Litt arbeid men da dropper vi å kopiere shoelace komponenter. Så må du bare registere riktige ikoner et sted i den applikasjonen hvor du skal bruke designsystemet som beskrevet i readme. 
Da antar jeg at du ikke trenger å overskrive/kopiere private metoder siden de er akkurat det samme som i shoelace repo, eller var det noe du trengte å endre i nve_handleSummaryKeyDown og nve_handleSummaryClick?

2024-04-16 08:21 UTC, tomapedersen commented
@amish1188 

- Sharp er så vidt jeg har skjønt det som skal brukes. Det er i alle fall det som står på Figma: https://www.figma.com/file/JA9IXcmhPvQIgdsFPr4ysB/03---Ikoner?node-id=155%3A683&mode=dev
- Jeg måtte endre Shoelace-render-metoden siden den er litt ulik. 
    - Det er ulike ikoner: SL viser "til høyre" og "nedover", men NVE skal bruke "nedover" og "oppover". 
    - Plasseringen er også ulik, shoelace har pilen til høyre, men vi har den til venstre
 - Endret ikke på de to metodene, men siden jeg ikke fant en bedre måte å gjøre om render-metoden så måtte jeg kopiere dem inn

2024-04-16 08:38 UTC, amish1188 commented
> @amish1188
> 
> * Sharp er så vidt jeg har skjønt det som skal brukes. Det er i alle fall det som står på Figma: https://www.figma.com/file/JA9IXcmhPvQIgdsFPr4ysB/03---Ikoner?node-id=155%3A683&mode=dev
> * Jeg måtte endre Shoelace-render-metoden siden den er litt ulik.
>   
>   * Det er ulike ikoner: SL viser "til høyre" og "nedover", men NVE skal bruke "nedover" og "oppover".
>   * Plasseringen er også ulik, shoelace har pilen til høyre, men vi har den til venstre
> * Endret ikke på de to metodene, men siden jeg ikke fant en bedre måte å gjøre om render-metoden så måtte jeg kopiere dem inn

Skjønner. Når det gjelder ikone plassering endringer så jeg tror det er kanskje vår designsystemet som burde tilpasses. Det er hvordan det fungerte så langt med andre komponenter (vi måte gi beskjed til designere at noe ikke kan gjøres for å unngå å skrive render på nytt), men selvfølgelig du kunne ikke vite det. @gruble er nå hovedansvarlig for ds så kanskje han kan svare bedre på det ;) Uansett så vi må sikkert avklare med designere hvilken type av ikoner vi skal bruke fordi det er en del uklarheter her tydeligvis. Alle andre komponenter er satt opp til å bruke Outlined som default så det kan være at dere vil legge merke til det når dere starter å bruke komponenter som select, checkbox eller dialog. Kan også våre at Sharp og Outlined pilen ikone er lik, og det spiller ingen rolle hvilken type vi bruker

2024-04-16 10:18 UTC, gruble requested changes
Bra at du er igang med å lage NVE-komponenter!

Det er som Marcin sier. 
Du har sikkert sett masse eksempler på at vi har overstyrt render() i andre komponenter, men vi har blitt klokere etterhvert. Vi ønsker å gjøre dette i minst mulig grad, både for å spare tid og unngå vedlikehold når Shoelace kommer med nye versjoner.
Disse problemstillingene er [beskrevet i Readme](https://github.com/NVE/Designsystem?tab=readme-ov-file#hvordan-tolke-design-i-figma).

Så ta en ekstra runde med Knut/Maren og få justert på designet i Figma så vi slipper masse kodeendringer pga. noe plassering/orientering av ikoner.

Når det gjelder valg av ikoner er jeg usikker, fordi jeg ikke har kompetanse på det. 
Hvis det er behov for avklaringer her, kanskje vi kan ta en prat med Knut og Marcin?

Jeg har ikke vurdert Storybook-dok'en ennå, tar dette når du har en ny versjon klar.

2024-04-17 05:01 UTC, tomapedersen commented
Shoelace vil ikke få flere versjoner (de har startet et nytt system, Web Awesome)

Men lar denne saken ligge død frem til design har sett på det

2024-04-17 07:55 UTC, gruble commented
> Shoelace vil ikke få flere versjoner (de har startet et nytt system, Web Awesome)
> 
Er klar over det. Jeg har ikke brukt mye tid på å vurdere hvilke konsekvenser det har for oss, men regner med at produktet (og koden) kommer til å levere videre, men med nytt navn, bare.

> Men lar denne saken ligge død frem til design har sett på det

Ok. Si ifra om du lurer på noe. Er ikke sikkert "design" plukker opp dette, så mulig du må snakke med dem direkte.

2024-07-04 06:39 UTC, closed without merging