AVN-223: nve-input
NVE/Designsystem pull request #18
Opened 2023-12-06 14:32 UTC by gruble

Da er nve-input klar til slakt.
Med på kjøpet får du også nve-label og nve-tooltip, siden nve-input trenger begge disse.
Takk til @Citaborg for god hjelp!

Jeg har rappet test-opplegget til Lars Thomas i #17. Synes dette er lett å jobbe med når man utvikler komponenter, og jeg tror det gir en bra demo for utviklere som skal bruke komponentene også, når vi får til å publisere test-appen. 
Ellers er det "bare" å kjøre `npm run dev` og åpne testsida i en nettleser  for dem som har utviklingsmiljø.

I nve-input kan vi antakelig slette en del mapping av sl-tokens når resultatet av den generelle mapping-jobben er på plass.

Jeg avventer dokumentasjon/veiledning på hvordan man skal dokumentere i Storybook før jeg evt. starter på Storybook-dokumentasjon.

2023-12-08 09:01 UTC, Citaborg commented on src/components/nve-input/nve-input.styles.ts
> +    --sl-input-border-width: 1px;
Her er det kanskje en nve-token som kan settes?

2023-12-11 10:13 UTC, amish1188 requested changes

2023-12-11 10:13 UTC, amish1188 commented on src/utils/slot.ts
> +/** Denne er basert på kildekoden til Shoelace.style */
fint at du bruker koden fra shoelace og at den fungerer :) jeg bare savner noe mer info på hvorfo vi må ha den egentlig. jeg ser den brukes i nve-label komponent men hadde vært enda bedre om man kunne vite med en gang hvorfor må vi faktisk ha den.

2023-12-11 10:36 UTC, gruble commented on src/components/nve-label/nve-label.styles.ts
> +    vertical-align: bottom;
Takk for tips!

2023-12-12 08:24 UTC, gruble commented on src/components/nve-input/nve-input.ts
> + * --sl-input-required-content
Enig

2023-12-12 08:25 UTC, gruble commented on src/components/nve-input/nve-input.ts
> + * Vil du ha info-ikon med hjelpetekst, putt en nve-label i label-slot.
Ja, jeg mener det er her vi bør dokumentere det, fordi dette vises i VS Code

2023-12-12 08:25 UTC, gruble commented on src/utils/slot.ts
> +/** Denne er basert på kildekoden til Shoelace.style */
Enig

2023-12-13 07:41 UTC, amish1188 commented on src/components/nve-input/nve-input.ts
> + * Vil du ha info-ikon med hjelpetekst, putt en nve-label i label-slot.
jeg tenker mer at siden du har demo fila som viser forskjellige varianter og en er med nve-label, kan ikke folk kun se der hvordan man kan oppnå det?

2023-12-18 13:45 UTC, merged