docs(updated info): Added text on different sites, color adustment an…
NVE/Designsystem pull request #195
Opened 2024-08-09 07:44 UTC by knutnve

docs(updated info): Added more text on different sites, color adjustment and new page: Universell Utforming.

2024-08-12 10:54 UTC, gruble requested changes
Fint!
Har kun spolt kjapt gjennom denne.
Har noen få kommentarer i enkelt-filer i tillegg til to kommentarer som gjelder generelt:

1. Flere steder leser det om "NVE og Varsom" som om NVE og Varsom var to forskjellige organisasjoner. Se f.eks. første avsnitt på sida om universell utforming: "NVE og Varsoms tjenester..." Dette synes jeg er villedende. Er ikke bare NVE og Varsom i denne sammenhengen to forskjellige design-tema? I så fall mener jeg det kun bør stå NVE når vi snakker om organisasjon eller ansvar.
2. Pull requests skal ha en norsk tittel som tydelig beskriver hva PR'en er. Du bør også skrive en bedre forklaring/beskrivelse av PR'en. Hvis du er tydeligere på hva PR'en er, får du bedre kommentarer.

To generelle kommenyt

2024-08-12 10:54 UTC, gruble commented on doc-site/introduction/designElements.md
> +Noen av variablene er tema-baserte, noe som betyr at de kan tilpasses din merkevare ved å bruke de fargene og preferansene du selv velger. Vi arbeider med en tema-bygger som skal gjøre det enklere fo
Her introduserer du begrepet `variablene` uten å forklare sammenhengen mellom design tokens og css-variable. Kanskje burde forklaringa på linje 13 flyttes før dette avsnittet?

2024-08-12 10:54 UTC, gruble commented on doc-site/introduction/designElements.md
> +Design Tokens er fleksible variabler som kan benyttes på tvers av ulike teknologier og designverktøy.
Fint med en forklaring. Kan du være mer konkret? Hva betyr "på tvers av ulike teknologier og designverktøy" i praksis?
Hadde det vært enklere om du kan noen eksempler?

2024-08-12 10:54 UTC, gruble commented on doc-site/introduction/designElements.md
> +I designsystemet har farger kontekstbaserte roller. Det vil si at når du brukere fargene, må du bruke de i riktig kontekst. F.eks: Vil det stå om fargen brukes i elementer med forgrunn eller bakgrunn
bruker (i linje 20)

2024-08-12 10:54 UTC, gruble commented on doc-site/introduction/designElements.md
>  Designsystemet samler og tilgjengeliggjør verktøy, filer, komponenter og designretningslinjer som brukes av designere og utviklere for å lage gode og konsekvente brukeropplevelser i NVE og Varsoms di
Typografi-avsnittet ser ikke ut som det er ferdig? Hva med å legge inn en TODO i stedet for en dummy-tekst?

2024-08-13 07:31 UTC, knutnve commented
Takk for feedback! Ja jeg fikser det @gruble !

2024-08-19 08:12 UTC, knutnve reviewed
Endret etter feedback. 
La til egene sider i designelementer og delt opp, siden det ble så mye tekst. La til mer bilder. 

_Sikkert litt rotete gjort men har ikke så erfaring i å jobbe med kode til Git_

2024-09-18 12:43 UTC, merged