PR: lagde message--card komponent
NVE/Designsystem pull request #198
Opened 2024-08-13 09:10 UTC by amish1188

Message-card ligner på alert men det er ikke det samme. message-card skal brukes som en lengre boks med teksten for  å gi brukere ekstra info i skjemaer f.eks. Jeg lagde den fordi vi skal bruke den i ds dokumentasjonen som tips, varsel bokser. 

CodeExamplePreview.vue ble endret til å bruke iife for å kjøre scripter. Grunnen er at når man kjører en script i global scopet lagrer variabler, og når man går til en annen side og kommer tilbake den klager at variabler allerede ble definert. Iife gjør at scopet er lokalt, og den blir ødelagt når vi bytter siden (du kan sjekke problemet i nve-alert f.eks der vi bruker en script for å lukke alerten). 

ComponentMethods begrenser nå visning av private og lit sine lifecycle metoder. Vi trenger ikke å vise dem.

Message-card lukk knappen gjør det automatisk at korter blir fjernet fra DOMen. Vi trenger ikke å beholde en gjemt komponent tenker jeg. Hvis vi mener at vi trenger å beholde den, vi kan alltid endre det. Samme anbefaler jeg å gjøre med alerten. Alert egentlig trenger å bli skrevet om til vår egen komponent uten å bruke shoelace. Grunnen er at teksten og tittelen brukes som :after og :before i cssen. Det gjør at man f.eks ikke kan selecte teksten i alerten og kopiere den. Alert komponent er veldig enkelt, og den vil ikke trenge så mye arbeid.

2024-08-14 14:45 UTC, gruble requested changes
Bra! Fine kodeeksempler og god forklaring i PR.
Jeg har en del kommentarer på språk og småplukk i markdown-fila, bare

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +Slot `subheader` brukes til å vise en ekstra tekst over headeren.
'tittelen' i stedet for 'headeren'

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +Ikonet er tilpasset varianten i utgangspunktet, men du kan velge ditt eget ikone ved bruk av `iconTitle`-attributen.
ikon

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +<nve-message-card iconTitle="pets" variant="primary" title="Hunden sier voff voff">
:-)

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +### Vise eller hjemme ikonet
'gjemme' eller 'skjule' er kanskje enda bedre

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +<nve-message-card showIcon="false" variant="primary" title="Ingen ikone"> Ikonet skal ikke vises </nve-message-card>
"Ingen ikon" i stedet for "Ingen ikone"

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +```
Ta gjerne med et kort med standard-ikon ved siden av / under, så det er lett å sammenligne marger, mellomrom etc.

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +## Eksempler
Hadde vært kjekt med et eksempel på bruk av html i kortet, slik du gjør i contribution.md

2024-08-14 14:45 UTC, gruble commented on doc-site/components/nve-message-card.md
> +<nve-message-card title="Tips">Skal du vise en popup-alert som viser f.eks. status på api-response, bruk nve-alert i stedet.</nve-message-card>
Jeg synes ikke det var helt tydelig hva forskjell på nve-message-card og nve-alert er. Kan du forklare dette på en annen måte?

2024-08-15 08:58 UTC, amish1188 commented on doc-site/components/nve-message-card.md
> +<nve-message-card style="box-shadow:var(--dropdown)" variant="neutral" title="Tittel">Neutral</nve-message-card>
jeg må fordi den er hvit og bakgrunnen er hvit, kræsjer ganske sterkt :P 
<img width="632" alt="Screenshot 2024-08-15 at 10 57 59" src="https://github.com/user-attachments/assets/e57ca8b5-5777-4a39-bfbd-4d073b9c09c6">
men kan lagge en kommentar hvorfor

2024-08-15 08:58 UTC, amish1188 commented on doc-site/components/nve-message-card.md
> +<nve-message-card style="box-shadow:var(--dropdown)" variant="neutral" title="Tittel">Neutral</nve-message-card>
eller kanskje vi kan endre codepreview bakgrunnsfarge til noe mer grå-ish

2024-08-15 09:02 UTC, amish1188 commented on doc-site/components/nve-message-card.md
> +```
hmm, men det er egentlig bare ikonen som endres i dette eksempelet. Det er ingen forskjell i marger og mellomrom.

2024-08-15 09:27 UTC, gruble commented on doc-site/components/nve-message-card.md
> +<nve-message-card style="box-shadow:var(--dropdown)" variant="neutral" title="Tittel">Neutral</nve-message-card>
Hva er vanlig bakgrunnsfarge i applikasjonene våre? Om den er hvit er det sikkert best å bruke hvit bakgrunn her også. Det holder fint med en kommentar på hvorfor du må style den altså.

2024-08-15 09:29 UTC, gruble commented on doc-site/components/nve-message-card.md
> +```
Nei, men det at det er ingen forskjell er også greit å se. Da får du testet og vist at marger og mellomrom ikke påvirkes av ikonet

2024-08-15 09:31 UTC, gruble commented on doc-site/components/nve-message-card.md
> +<nve-message-card variant="primary" title="Tittel">Primary</nve-message-card>
Tja... jeg har valgt å droppe å ha med default properties for en del komponenter, bare for å gjøre koden enklest mulig.  Men ikke viktig. 
Men i andre eksempler hvor variant ikke er interessant, blir det bare støy å spesifisere variant, synes jeg.
Men da må man huske å skrive hva som er default i dokumentasjonen.

2024-08-15 09:33 UTC, amish1188 commented on doc-site/components/nve-message-card.md
> +<nve-message-card variant="primary" title="Tittel">Primary</nve-message-card>
okei, da lar jeg variant stå i variant seksjonen men dropper alle andre steder

2024-08-15 10:35 UTC, gruble commented on doc-site/components/nve-message-card.md
> +```
Ah, jeg var en smule rotete i kommentaren min. Jeg mente å vise et kort UTEN ikon under et kort med ikon, så man kunne se forskjellen. Beklager! Ikke viktig:)

2024-08-15 10:37 UTC, gruble commented on doc-site/components/nve-message-card.md
> +  Vi har ingen støtte på denne egenskapen.
Glemte du denne?

2024-08-15 12:09 UTC, merged