Kilden til status på komponentene ligger nå i Komponentoversikt.md
NVE/Designsystem pull request #205
Opened 2024-08-14 12:25 UTC by gruble

Har gjort noen endringer i komponent-oversikten:
- denne henter nå sine data fra `Komponentoversikt.md`
- For å legge til komponenter eller endre status på en komponent, rediger lista som sendes inn til `ComponentOverview` i `Komponentoversikt.md`. Dette kan gjøres direkte fra sida ved å klikke på `Rediger denne sida i Github` (men ikke før denne PR'en fullføres)
- Har forenklet strukturen på det vi trenger for å vise lista, sammenlignet med `componentStatuses.js`, for å gjøre det lettere å vedlikeholde
- Kun komponenter vi har laget, har link, så vi slipper døde linker
- Jeg har fjernet statusen `Mangler link i Figma` og heller latt være å vise link-ikonet når vi mangler en link
- Lista er nå sortert alfabetisk på komponent-navn, så det stemmer med rekkefølgen i menyen under 'Komponenter'. 
- Beskrivelse på komponenten vises foreløpig ikke. Vi kan ta inn dette ved behov

- [ ] Hadde vært kjekt å kunne sortere på hver av status-kolonnene også
- [ ] Kunne ønsket meg noe lavere rad-høyde

2024-08-15 13:02 UTC, amish1188 requested changes
Bra løsning. Vi må huske å la designere teste den etter merging. Har bare noen små kommentarer.

2024-08-15 13:13 UTC, gruble commented on doc-site/.vitepress/theme/components/ComponentOverview.vue
> +export interface ComponentStatus {
Det visste jeg ikke. Ok!

2024-08-19 11:02 UTC, NVEJoel commented
Ser bra ut! Snakkat med Knut om upplægget og han synes det også er bra. 
To ønskemål: 
* En til kolumn som heter "Git issue" dær tanken er att designerna kan lægga in Github issue lænken dær man beskriver hva som må gøras eller ændras. 
* Kan man få de olika status i raden Totalt antall komponenter på rad istællet så det blir tydligare? 
* Vore snyggt med en Søk funktion men det kan vi lægga til senare.

2024-08-20 06:51 UTC, knutnve commented
Innspill:

- Skal vi fjerne nve- foran komponentnavn for å gjøre tabellen enda mer lesbar og oversiktlig? 
- Kunne vi lagt til git hub logo eller figma logo dersom det er link til de? 
- Om vi har en kommentar som burde være synlig, kan vi legge til rette for det også

Typ sånn?
<img width="564" alt="Screenshot 2024-08-20 at 08 48 26" src="https://github.com/user-attachments/assets/4c5cc6ef-53b7-4031-b9fc-4f0b35b652c9">

2024-08-20 16:10 UTC, gruble commented
> Innspill:
> 
> * Skal vi fjerne nve- foran komponentnavn for å gjøre tabellen enda mer lesbar og oversiktlig?

Vi velger å ikke fjerne nve-foran komponentnavn foreløpig fordi det krever at vi må ha et ekstra navnefelt på komponenten. Kan legges til seinere hvis vi ønsker ha det.

> * Kunne vi lagt til git hub logo eller figma logo dersom det er link til de?

Github-logo trenger vi nok ikke. Tror ikke det er så relevant med link til kildekoden til komponenten. Men vi har allerede link til brukerveiledninga for komponenten. Figma-logo har vi. Dessverre fant jeg ikke sort-hvitt-svg'en for logoen i Figma, så beholder den vi hadde i farger.

> * Om vi har en kommentar som burde være synlig, kan vi legge til rette for det også

Venter litt med denne, men tar det inn hvis vi får til å oppdatere status manuelt. Det er lett å legge inn seinere.

2024-08-20 16:14 UTC, gruble commented
> Ser bra ut! Snakkat med Knut om upplægget og han synes det også er bra. To ønskemål:
> 
> * En til kolumn som heter "Git issue" dær tanken er att designerna kan lægga in Github issue lænken dær man beskriver hva som må gøras eller ændras.
> * Kan man få de olika status i raden Totalt antall komponenter på rad istællet så det blir tydligare?
> * Vore snyggt med en Søk funktion men det kan vi lægga til senare.

Fikset linjeskift mellom hver status. Jeg har laget en egen sak på det med å linke inn issues (#220).

2024-08-20 16:24 UTC, merged