Feature/nve dropdown
NVE/Designsystem pull request #21
Opened 2023-12-07 09:53 UTC by erik-edin

Mangler versjon med Radio Button, Toggle og Badge da de ikke er lagd ennå.

Det er ikke tatt høyde for de forskjellige varianter som focus, hover og disable da jeg fikk beskjed om å vente med det. 

![image](https://github.com/NVE/Designsystem/assets/148051877/12d43fbf-fb9e-400e-a969-69f430c31ef4)

2023-12-08 09:09 UTC, Citaborg commented on src/components/nve-dropdown/nve-dropdown.ts
> +  static styles = css`
Bruke det fra import av styles-filen

2023-12-08 09:13 UTC, Citaborg commented on src/components/nve-menu-item.ts
> +  @property({ type: Boolean, reflect: true }) dividerTop: boolean = false;
trenger ikke sette = false da det er default. Alternativt kan du sette = false og da trenger du ikke : boolen siden det er gitt av false :-)

2023-12-08 09:14 UTC, Citaborg commented on src/components/nve-menu-item.ts
> +  static get styles() {
flytte ut i .styles-fil?

2023-12-08 09:15 UTC, Citaborg commented on src/components/nve-menu-item.ts
> +       /* border-radius: var(--border-radius-small, 0.25rem);*/
ta bort kommentert kode

2023-12-08 09:17 UTC, Citaborg commented on src/components/nve-menu-item.ts
> +        margin-inline-end:0px;
0 skal ikke ha/trenger ikke benevning. Ev bruk unset

2023-12-08 09:18 UTC, Citaborg commented on src/components/nve-menu-item.ts
> +        font-family: Source Sans Pro;
Font-innstillinger må hentes fra token

2023-12-11 14:26 UTC, amish1188 requested changes

2023-12-18 11:55 UTC, knutnve commented
Endel kommentarer

![Frame 1111](https://github.com/NVE/Designsystem/assets/129265201/d2e4ff92-e84d-4bc8-9a3d-b78680a31b84)

2024-01-03 15:47 UTC, amish1188 approved these changes

2024-01-03 15:47 UTC, amish1188 commented on src/components/nve-menu-item/nve-menu-item-styles.ts
> +    border: var(--border-width-strong, 2px) solid var(--Interactive-Primary-Foreground-Border-Focus, #008FFB);
det er noe gjern med border her. ser ut at box sizing ikke fungerer og item sprer seg 2px som gjør at man ser en mosjon inni item på focus. Ikke bra. La oss bruke box-shadow: inset 0 0 0 var(--border-width-strong, 2px) var(--Interactive-Primary-Foreground-Border-Focus, #008ffb); istedenfor border her.

2024-01-03 15:49 UTC, amish1188 reviewed
Bra! Bare en liten ting :)

2024-01-03 15:49 UTC, amish1188 requested changes
Bra! Bare en liten ting :)

2024-01-04 07:13 UTC, joergenlampe approved these changes

2024-01-04 09:12 UTC, amish1188 approved these changes

2024-01-04 09:15 UTC, merged