Laget en nve-chip. Kan vise enkel info, og kan ha en lukke-knapp
NVE/Designsystem pull request #213
Opened 2024-08-19 11:25 UTC by tomapedersen

2024-08-20 12:50 UTC, amish1188 requested changes
En veldig fin komponent :) Jeg har bare et par kommentarer og meninger, og jeg vil gjerne at flere gir sin innsats. Jeg er litt usikker på hover-effekten på lukkeknappen. Jeg er usikker på hvorfor det er hele knappen som endrer farge, kanskje det ville vært bedre å bare ha en sirkel rundt selve knappen og legge effekten på den? Jeg tror noe lignende allerede finnes i alert og dialog.

2024-08-20 12:51 UTC, knutnve commented
Tilbakemelding:

- Vi må gjøre om hover effekten til å kun gjelde bakgrunnsfargen til icon boksen, med hjørneradius small. 
- La til bilde som forklarer hvilken hover farge som skal være aktiv, hvis du hovrer på "x"en. 

<img width="989" alt="Screenshot 2024-08-20 at 14 50 31" src="https://github.com/user-attachments/assets/6541d1df-4788-446d-95fa-b2d7c0138092">

2024-08-20 12:52 UTC, knutnve requested changes
Tilbakemelding:

- Vi må gjøre om hover effekten til å kun gjelde bakgrunnsfargen til icon boksen, med hjørneradius small.


La til bilde som forklarer hvilken hover farge som skal være aktiv, hvis du hovrer på "x"en.

<img width="993" alt="Screenshot 2024-08-20 at 14 52 06" src="https://github.com/user-attachments/assets/dfc4fc5c-37bf-4ab5-8406-e8b574829318">

2024-08-20 14:42 UTC, gruble commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
Jeg synes det er ryddig hvis vi gjør det likt som nve-message-card og nve-alert.

2024-08-21 04:58 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
"emphasized" er nok ok, men "low" liker jeg ikke, den er veldig lite deskriptiv. Men siden den er brukt andre steder så er det kanskje best.

Grunnen til at jeg gjorde det slik er at når man har ulike varianter så er det vel alltid bedre med én property som sier hvilken det skal være enn å ha en rekke med bools. Det å ha "low", "emphasized" som bools er for meg det samme som å ha variant som en rekke med bools istedenfor en string-verdi. Rekke med bools som ikke kan kombineres er en definitiv code smell for meg

2024-08-21 05:01 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: false, attribute: true }) 'extra-text' = '';
Gjorde det på Shoelace-måten. Det er nokså mange komponenter som har akkurat dette, for eksempel `label`, `help-text` på input

2024-08-21 05:26 UTC, tomapedersen commented
@knutnve : Ser nå at Figma bruker "tag", ikke "chip". Siden `tag` er et ord i html så foreslår jeg at vi heller døper om komponenten i Figma

2024-08-21 05:39 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.styles.ts
> +  .chip {
Gjort

2024-08-21 05:43 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +    const varName = `${this.emphasis}-${this.variant}`;
Endret. Ble 90 ekstra linjer css ( 5 varianter, 3 emphasis-varianter, 6 linjer css per)

2024-08-21 05:43 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: Boolean, reflect: false }) 'has-close': boolean = false;
Endret

2024-08-21 05:46 UTC, tomapedersen commented on doc-site/components/nve-chip.md
> +---
Den kjøres vel som en del av `npm run build` som jeg kjørte underveis?

2024-08-21 05:47 UTC, tomapedersen commented
Gjort en del endringer nå. Men ikke endret `emphasis` eller extra-text attribute/slot; se kommentarer

@gruble @amish1188

2024-08-21 06:27 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
La inn en kommentar på FUX Forum om dette nå

2024-08-21 06:42 UTC, NVEJoel commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
Hørde att  @gruble  og @tomapedersen  hade snakkat om detta på kontoret. Vi kan gå igenom vad ni kom øverrens om på møtet idag.

2024-08-21 06:54 UTC, NVEJoel commented on doc-site/components/nve-chip.md
> +---
Vi kanske kan endra texten i readMe "Når du kjører opp test/dokumentasjons-applikasjonen, blir koden scannet og metadata + JsDoc lagret i `custom-elements.json`. Du kan også generere fila manuelt med `npm run manifest`. Dokumentasjons-applikasjonen bruker denne fila."    
så att det blir tydligt att npm run build æven kør npm run manifest.

2024-08-21 06:57 UTC, NVEJoel commented
@knutnve  Vi borde se øver færgerna og kontrasterna. Kombinationen vi bruker idag ger accessability varningar "Ensure the contrast between foreground and background colors meets WCAG 2 AA minimum contrast ratio thresholds" .

2024-08-21 07:08 UTC, amish1188 commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
Det gir mening. Har ikke  tenkt på det. Jeg ser at alerten har kun `emphasized` intensivitet og badge kun `low`. Da jeg startet med badgen sto det low i figma. Hvis du mener low ikke er beskrivende nok, vi burde kanskje endre low til weak på badgen og. 
Kan vi i hvert fall endre navnet på selve property fra emphasis til intensity/tone/accent kanskje?

2024-08-21 07:16 UTC, amish1188 commented on doc-site/components/nve-chip.md
> +---
Den burde faktisk kjøre med bygg scriptet. Det må være noe feil der. Jeg bare merket at jsdocs beksrivelsen finnes ikke i komponenten din når jeg åpner demo appen. Men det er ikke noe vi skal fikse i denne PRen ;)

2024-08-21 07:16 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
Ja, selve navngivingen kan absolutt diskuteres. Det er også ulik bruk i css-variablene (emphasized, default, subtle) og hva som brukes i Figma (emphasized, subtle, weak). Bør standardiseres overalt.

2024-08-21 07:23 UTC, amish1188 commented on src/components/nve-chip/nve-chip.styles.ts
> +`;
nve-icon har ikke størrelsen bestemt i designsystemet. Kanskje vi burde gjøre noe med det. Den arver font-size fra foreldrene sine. kan du endre font-size på nve-icon til 20px som det ligner de i figma?

2024-08-21 07:29 UTC, amish1188 requested changes

2024-08-21 07:29 UTC, amish1188 commented on src/components/nve-chip/nve-chip.styles.ts
> +`;
Okei jeg ser nå at du skrev 
``` nve-icon {
    font-size: var(--font-size-small);
  }
  ```
kan du fjerne slotted delen? Den er ikke i et slot så slotted ikke fungerer

2024-08-21 07:32 UTC, knutnve commented
> @knutnve : Ser nå at Figma bruker "tag", ikke "chip". Siden `tag` er et ord i html så foreslår jeg at vi heller døper om komponenten i Figma

Den heter tag i figma og i shoelace. Om det kommer det i konflikt med tag i html, det kan ikk jeg ta stilling til. Så det må dere bestemme. Da må vi endre navn.

2024-08-21 07:35 UTC, amish1188 commented
bare en liten info/tips: Den skal ikke komme i konflikt med html tag fordi vi bruker nve-tag

2024-08-21 07:36 UTC, tomapedersen commented on doc-site/components/nve-chip.md
> +---
custom-elements.json ligger i dist-mappen.
.gitignore sier at dist-mappen ikke skal sjekkes inn

Tror de to linjene forklarer hvorfor den ikke er med 😄

2024-08-21 07:59 UTC, tomapedersen commented
@amish1188 , ja konflikten er ikke kodemessig, men "uklarhet om hva vi snakker om"-konflikt. `nve-tag` kan forstås som "tag i nve-design-systemet", for eksempel `<nve-button>` er en "tag med nve-prefiks", eller en "nve-tag"

2024-08-21 09:40 UTC, amish1188 commented
@tomapedersen skjønner. Jeg syns fortsatt det ikke er så problematisk å kalle komponenten som nve-tag (vi bruker tag begrepet nesten aldri tenker jeg :P), men samtidig har jeg ikke noe mening om hvordan komponenten skal hete. Både tag og chip fungerer for meg. Jeg vil tro at @knutnve tenkte o kalle den tag siden det allerede finnes en komponent i shoelace, men siden du lagde komponent uten å arve fra shoelace, spiller ingen rolle hvordan den heter. Bare så at vi har lik navn både her og i figma. Vil tro det er enklere å bytte navn i figma en i kode (til nve-tag) :P

2024-08-21 12:50 UTC, tomapedersen commented on src/components/nve-chip/nve-chip.component.ts
> +  @property({ type: String, reflect: true }) emphasis: 'emphasized' | 'subtle' | 'default' = 'default';
Etter å ha snakket med designer bruker vi nå `saturation=["emphasized"|"default"|"subtle"]

2024-08-22 05:02 UTC, merged