Tooltip er nå stylet med nve-farger (variant og saturation)
NVE/Designsystem pull request #225
Opened 2024-08-22 08:41 UTC by tomapedersen

La til de samme variantene og saturation som vi bruker andre steder.
Fikset samtidig også verdiene for padding, font etc slik at disse er som i Designsystemet
La til en del flere eksempler i md-filen også for å gjøre et par ting klarere

2024-08-22 08:44 UTC, tomapedersen commented
Pinger @knutnve først for å se på design

2024-08-23 09:06 UTC, tomapedersen commented
Designer har nå gått igjennom den, så setter den videre for kode-PR

2024-08-23 12:01 UTC, amish1188 commented on doc-site/components/nve-tooltip.md
> +  style="display: grid; gap: var(--spacing-small); grid-template-columns: auto 1fr 1fr 1fr; align-items: center; justify-content: center;"
vi må kanskje lage en slags tabell og style den med css klasser, fordi jeg ser at vi sliter (må skrive extra css i eksemplarer) ganske med riktig komponent visning i rader. Jeg lager en issue på den

2024-08-23 12:02 UTC, amish1188 approved these changes

2024-08-26 07:12 UTC, knutnve commented
Ferdig med design. Den kan merges om alt er i orden med kode. :)

2024-08-27 13:26 UTC, gruble requested changes
Bra med masse gode eksempler!

Jeg har kommentert det et sted i koden, men jeg skriver det her siden det egentlig gjelder generelt. Du bruker mye styling i eksemplene, noe som gjør det vanskeligere å se i koden hvilke egenskaper du prøver å demonstrere. Hadde det vært mulig å redusere mengden styling?
Jeg forsøkte å ta bort inline styling på nve-tooltip i et par eksempler for å gjøre koden lettere å lese, men da så jeg at tooltip'en ikke ble sentrert på komponenten lengre. 
![image](https://github.com/user-attachments/assets/cde5a7f8-63d2-4c7c-a2f4-8acf79fed8c4)
Hvorfor skjer dette?
Burde vi håndtert dette inni selve komponenten eller justere på CodeExamplePreview-komponenten så man ikke påvirker plasseringa av tooltip'en? 
Eller er det slik komponenten vil oppføre seg i et vanlig scenario?
I så fall synes jeg vi burde skrive noe om dette.

2024-08-27 13:38 UTC, gruble commented on doc-site/components/nve-tooltip.md
> +```
Jeg tror denne så helt grei ut og lettere å lese uten styling på `nve-tooltip`?
![image](https://github.com/user-attachments/assets/0ef3b57a-0856-4506-a7fa-1dd31f9c6f23)

2024-08-28 09:46 UTC, tomapedersen commented on doc-site/components/nve-tooltip.md
>  ```
nei, men det måtte til grunnet manglende css i CodeExamplePreview

2024-08-28 09:47 UTC, tomapedersen commented
Skrev om CodeExamplePreview noe slik at den kan få inn et par props slik at den støtter grid/flex med align/justify

2024-08-28 09:48 UTC, tomapedersen commented on doc-site/components/nve-tooltip.md
> +  style="display: grid; gap: var(--spacing-small); grid-template-columns: auto 1fr 1fr 1fr; align-items: center; justify-content: center;"
Fikset det med å legge til noen props i CodeExamplePreview

2024-08-28 09:51 UTC, merged