PR - Storybook dokumentasjon
NVE/Designsystem pull request #38
Opened 2023-12-11 15:44 UTC by joergenlampe

2023-12-12 09:32 UTC, amish1188 requested changes

2023-12-12 09:32 UTC, amish1188 commented on src/stories/NveButton.stories.ts
> +      options: ['x-small', 'small', 'medium', 'large'],
jeg trodde vi ble enige (sammen med Knut) om å ikke ha x-small

2023-12-12 09:32 UTC, amish1188 commented on src/stories/NveButton.stories.ts
> +      options: ['primary', 'default', 'neutral', 'large'],
large ;)

2023-12-12 09:32 UTC, amish1188 commented on src/stories/NveButton.stories.ts
> +    variant: {
det ser sånn utt at man kan bruke outlined kontroller på alle varianter. vi burde kanskje begrense den kun til neutral (finnes ikke outlined primary eller secondary i ds)? Jeg fant en løsning som kunne hjelpe oss med det. I argTypes du kan legge til `outline: { control: 'boolean', if: { arg: 'variant', eq: 'neutral' } },`

2023-12-12 09:32 UTC, amish1188 commented on src/stories/NveButton.ts
> +    size: 'medium' | 'large' | 'small' | 'x-small',
x-small trengs ikke (hvis jeg husker riktig)

2023-12-12 11:16 UTC, amish1188 commented on dist/assets/index-adNgpBcF.css
trenger vi å sjekke det inn? dist mappe ble lagt til gitignore i input og radio PR, så main fortsatt vil ta denne mappa med :/

2023-12-14 07:38 UTC, joergenlampe commented on src/stories/NveButton.stories.ts
> +    variant: {
det fungerte bra!

2023-12-14 07:38 UTC, joergenlampe commented on src/stories/NveButton.stories.ts
> +      options: ['primary', 'default', 'neutral', 'large'],
fikset

2023-12-18 11:10 UTC, joergenlampe commented on dist/assets/index-adNgpBcF.css
har slettet filen

2023-12-18 12:18 UTC, gruble approved these changes
Bra!

2023-12-18 12:40 UTC, merged