Oppdatert registrer og resett disabled-state på gruppenivå
NVE/Designsystem pull request #47
Opened 2023-12-18 14:52 UTC by Citaborg

Lagt til 
- obligatorisk*
- størrelse i storybook
- registrering av initiell disable-state 
- og lagring av state når gruppen settes til disabled
- resett til lagret state når gruppen settes til ikke disablet

2023-12-19 07:45 UTC, gruble approved these changes
Det ser fornuftig ut.
Den funksjonen med å huske om hver enkelt radioknapp var deaktivert hadde nesten fortjent en enhetstest. Vanskelig for meg å teste det uten å kode i hvert fall:)

2023-12-19 13:35 UTC, amish1188 requested changes
Siden vi man kan vise label med ikone og tooltip, jeg tror vi burde vise en eksempel på hvordan kan man bruke nve-label i et slot her kanskje (i hvert fall huske å vise det et sted i dokumentasjonen)? 
Jeg ser at vi blander litt filnavngivning, noe som vi kanskje burde også spesifisere i dokumentasjone. Men siden de fleste filene i hver komponent mappe er nå lagret som
- nve-component.ts (hoved ts fil)
- nve-component-demo.ts (demo fil)
- nve-component.styles.ts (styling) 
kan vi følge dette mønsteret?

2023-12-19 13:39 UTC, Citaborg commented
> Siden vi man kan vise label med ikone og tooltip, jeg tror vi burde vise en eksempel på hvordan kan man bruke nve-label i et slot her kanskje (i hvert fall huske å vise det et sted i dokumentasjonen)? Jeg ser at vi blander litt filnavngivning, noe som vi kanskje burde også spesifisere i dokumentasjone. Men siden de fleste filene i hver komponent mappe er nå lagret som
> 
> * nve-component.ts (hoved ts fil)
> * nve-component-demo.ts (demo fil)
> * nve-component.styles.ts (styling)
>   kan vi følge dette mønsteret?

Hvis du ser litt lenger og titter på filene i storybook, så er det flere steder gjenbrukt samme navn på fil. Så lenge det er slik synes jeg komponenten kan hete nve-komponentnavn.component.ts

2023-12-19 13:46 UTC, amish1188 commented
> > Siden vi man kan vise label med ikone og tooltip, jeg tror vi burde vise en eksempel på hvordan kan man bruke nve-label i et slot her kanskje (i hvert fall huske å vise det et sted i dokumentasjonen)? Jeg ser at vi blander litt filnavngivning, noe som vi kanskje burde også spesifisere i dokumentasjone. Men siden de fleste filene i hver komponent mappe er nå lagret som
> > 
> > * nve-component.ts (hoved ts fil)
> > * nve-component-demo.ts (demo fil)
> > * nve-component.styles.ts (styling)
> >   kan vi følge dette mønsteret?
> 
> Hvis du ser litt lenger og titter på filene i storybook, så er det flere steder gjenbrukt samme navn på fil. Så lenge det er slik synes jeg komponenten kan hete nve-komponentnavn.component.ts

i storybook bruker vi PascalCase mens våre filene skrives med bindestrekk. jeg vet ikke. jeg foretrekker kortere navn på filene selv, og så de fleste skriver kun nve-component.ts på filene deres. i tillegg i vs code blir alle .component filer vurdert som angular filer, og det vises angular ikone ved siden :P

2023-12-19 13:49 UTC, amish1188 commented
> > Siden vi man kan vise label med ikone og tooltip, jeg tror vi burde vise en eksempel på hvordan kan man bruke nve-label i et slot her kanskje (i hvert fall huske å vise det et sted i dokumentasjonen)? Jeg ser at vi blander litt filnavngivning, noe som vi kanskje burde også spesifisere i dokumentasjone. Men siden de fleste filene i hver komponent mappe er nå lagret som
> > 
> > * nve-component.ts (hoved ts fil)
> > * nve-component-demo.ts (demo fil)
> > * nve-component.styles.ts (styling)
> >   kan vi følge dette mønsteret?
> 
> Hvis du ser litt lenger og titter på filene i storybook, så er det flere steder gjenbrukt samme navn på fil. Så lenge det er slik synes jeg komponenten kan hete nve-komponentnavn.component.ts

vi kan endre til .component.ts men da la oss bruke -demo på filene med html fila, fordi jeg vil tro at demo fil er nå hoved fil i mappa

2023-12-21 12:36 UTC, amish1188 approved these changes

2023-12-21 12:45 UTC, merged