PR: updated packaging, documentation and folder structure
NVE/Designsystem pull request #68
Opened 2023-12-28 15:26 UTC by amish1188

Nå skal dist mappe inneholde kun bundlet prosjekt (komponenter), css fil med alle token varianter og global.css fil, og src mappe med kun komponenter. 

For å bygge bibliotek på en riktig måte må vi inkludere dist mappe (med bundled prosjekt) i publisering. Ellers skal pakken ikke fungere på en riktig måte (bl.a. node modules skal ikke med som f.eks. gjør at ts dekoratorer ikke fungerer som de burde).  Per i dag skjer det ikke fordi vi ignorerer dist mappe i .gitignore mappe. Hvis biblioteket ikke inneholder .npmignore fil, .gitignore er tatt som default (derfor dist blir ignorert). 
Jeg oppdaterte viteconfig fil så at den bundler kun src/index.ts fil (altså alle komponenter som vi eksporterer) og at bundlet fil alltid heter nve-designsystem. Vi oppretter også umd bundled fil som støtter eldre nettlesere der hvor esmodules ikke støttes, men også andre miljøer som node.js.

I rollupOptions måte jeg la til noen dependencies så at umd packaging skjønner hva vi snakker om og at den burde insta. 

Det vat litt problemer med å lage type fil (.d.ts) under bygging som burde bli opprettet som default, derfor installerte jeg vite-plugin-dts for å sikre at den kjøres. Vi trenger types ( "declaration": true, "emitDeclarationOnly": true, i tsconfig sikrer at de opprettes) for å vise dem på en riktig måte når man importerer komponenter i andre prosjekter. 

Jeg lagde en script build.js fordi det var ganske mange filkopiering og npm script i package.json startet å se litt stygt ut. Kan være at build.js skal utvides senere enda mer, så det er kanskje lurt å ha alt i en separat .js fil istedenfor. 

I package.json lagde jeg exports seksjon som forteller pakken hvilke filer/mapper kan brukes av eksterne brukere.  

Jeg endret fil struktur som vi snakket om, altså alle komponenter har nå .components.ts suffix osv.

Jeg oppdaterte dokumentasjon nå. Viktig steg er å teste pakke lokalt ved å installere zippet pakke som reflekterer hvordan alt skal fungere akkurat som man hadde installert det. Det er bedre måte å teste med npm pack enn med npm link. 

La også tgz filer til .gitignore i tilfelle folk glemmer å slette test pakker før de pusher til repo :P

2024-01-02 11:38 UTC, gruble reviewed
Bra jobba!
Jeg fikk til å bruke komponentene i Abonner ved å følge oppskiften.
Har en del kommentarer, men mesteparten er småplukk.
Det viktigste er kanskje å få med global.css

2024-01-02 11:38 UTC, gruble commented on src/index.ts
nve-alert skal kanskje være med her?
Får denne når jeg prøver å importere den i Abonner:
The requested module '/node_modules/.vite/deps/nve-designsystem.js?v=7d223b23' does not provide an export named 'NveAlert'

2024-01-02 11:38 UTC, gruble commented on src/index.ts
> +import './styles/global.css';
Denne blir ikke med når jeg pakker prosjektet. Må fortsatt importere den manuelt i Abonner. Kunne vi heller importert den i nve.css, f.eks.?

2024-01-02 12:23 UTC, amish1188 commented on package.json
> +    "cpy": "^11.0.0",
godt spørsmål. vi kan sikkert flytte de fleste til devdeps

2024-01-02 13:19 UTC, amish1188 commented on README.md
> +
litt usikker på hva du mener med export = true

2024-01-02 13:19 UTC, amish1188 commented on README.md
> +5. Kjør `npm  i` for å installere designsystem pakken
stemmer. bruker det slik selv :P

2024-01-02 14:50 UTC, amish1188 commented on src/index.ts
oppdatert

2024-01-02 14:50 UTC, amish1188 commented on src/index.ts
> +import './styles/global.css';
den er nå bundlet i js filer. man trenger ikke å importere global.css noe lenger

2024-01-03 08:40 UTC, gruble requested changes
Nå ser det ut som tgz-pakka inneholder alle filene i prosjektet. 
![image](https://github.com/NVE/Designsystem/assets/71138449/58d45b3a-e312-405b-bec1-e99bfc201354)
Var det meninga?
Jeg får heller ikke komponentene til å virke i Abonner:
![image](https://github.com/NVE/Designsystem/assets/71138449/05a0492b-541f-4799-bdfe-daf836649aa2)

Og hvis det er sånn at automatisk publisering vil slutte å virke når vi fullfører denne PR, må vi fikse det før PR godkjennes.

2024-01-03 08:40 UTC, gruble commented on README.md
> +
Det forstår jeg. Jeg mente reflect:true

2024-01-03 08:40 UTC, gruble commented on scripts/build.js
> +//Brukes til å kjøre bygg med fil kopiering
Bygger prosjektet og kopierer filer som må ligge ved biblioteket til dist-mappa

2024-01-03 09:49 UTC, gruble requested changes

2024-01-03 09:49 UTC, gruble commented on README.md
> +4. Kjør `npm  i` + kopiert .tgz fil full pathen
Kjør `npm i` <nve-designsystem-x.y.z.tgz med full sti>

2024-01-03 09:49 UTC, gruble commented on scripts/build.js
> +  return cpy('src/components/**/*', 'dist/components/', { concurrency: 100 });
Denne får med seg .demo.ts-filene. De trenger vi vel ikke å distribuere?

2024-01-03 09:49 UTC, gruble commented on README.md
> +2. Kjør `npm pack`. En .tgz fil med pakken navn og versjon burde dukke opp i root mappe
nve-designsystem-x.y.z.tgz lagres i dist-mappa

2024-01-03 09:49 UTC, gruble commented on README.md
> +Før man pusher til main er det lurt å teste pakke lokalt. Med `npm pack` kan man teste hvordan pakken oppfører seg akkurat på samme måte som etter publisering. For å lage en nve-designsystem pakke lo
For å **teste** en nve-designsystem pakke lokalt

2024-01-03 09:49 UTC, gruble commented on scripts/build.js
> +await nextTask('Building the project', () => {
Husk å slette alle filer i dist-mappa først

2024-01-04 09:34 UTC, joergenlampe approved these changes

2024-01-04 15:22 UTC, gruble approved these changes

2024-01-04 15:22 UTC, merged