PR: AVN-289 basic input validering
NVE/Designsystem pull request #79
Opened 2024-01-09 13:48 UTC by amish1188

Test i formen
Man kan enten bruke constraint validering med attributer, eller bruke reaktivt isvalid attribute istedenfor.
Man trenger ikke å bruke required for å vise requiredLabel hvis man velger å validere med isvalid, men da må man sikre at requiredLabel har noe verdi.
Hvis det finnes noe verdi fra før, klarer jeg ikke å validere det med en gang komponent er på plass, det er fordi shoelace form controller overskriver noen verdier som gjør at det er vanskelig å skrive en meningsfull logikk. Derfor dropper jeg det. 
Input felt blir breddere når feil ikone vises. Forklart i koden. Man burde kanskje sette noe bestemt bredde eller noe? 
Gjerne test i varsom appen siden reaktive properties går ikke i lit appen som de er

2024-01-10 14:03 UTC, gruble requested changes
Veldig bra du har fått til å vise feilmeldinger slik designerne ønsker.
Jeg synes isvalid-propertyen er grei å bruke når jeg skjønte hvordan jeg skulle gjøre det i Vue. 
Som et alternativ til å bruke isvalid og errorMessage har jeg nå testet [Shoelace sin måte å tilby "custom"-validering på](https://shoelace.style/getting-started/form-controls#custom-error-messages), som virket ganske enkel. Men denne funker ikke som den burde synes jeg:
- feilmeldingen vises som "undefined"
- feilmeldingen vises eller nullstilles først når man setter feltet i fokus
Her er koden jeg prøvde:
```
<template class="home-view">
  <form>
    <nve-input
      ref="myInputComponent"
      :value="myInputValue"
      @input="myInputValue = $event.target.value"
      label="Svaret på livet, universet og alt"
    >
    </nve-input>
    <nve-button @click="validate">Sjekk svaret</nve-button>
  </form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { NveInput, NveButton } from 'nve-designsystem';

const myInputComponent = ref();
const myInputValue = ref('');

const validate = () => {
  const valid = myInputValue.value == '42';
  if (!valid) {
    myInputComponent.value.setCustomValidity('Feil svar');
  } else {
    myInputComponent.value.setCustomValidity('');
  }
};
</script>
```
Det er mulig jeg bruker det feil, altså!
Det er bra med enkle valideringsmetoder, men jeg synes vi også bør støtte Shoelace sin standard validering så godt det lar seg gjøre.

Jeg har også en del kommentarer på struktur og særlig dokumentasjon. Har vært litt ekstra pirkete denne gangen, ikke ta det personlig!-)

2024-01-10 14:46 UTC, amish1188 commented
> Veldig bra du har fått til å vise feilmeldinger slik designerne ønsker. Jeg synes isvalid-propertyen er grei å bruke når jeg skjønte hvordan jeg skulle gjøre det i Vue. Som et alternativ til å bruke isvalid og errorMessage har jeg nå testet [Shoelace sin måte å tilby "custom"-validering på](https://shoelace.style/getting-started/form-controls#custom-error-messages), som virket ganske enkel. Men denne funker ikke som den burde synes jeg:
> 
> * feilmeldingen vises som "undefined"
> * feilmeldingen vises eller nullstilles først når man setter feltet i fokus
> 
> Her er koden jeg prøvde:
> 
> ```
> <template class="home-view">
>   <form>
>     <nve-input
>       ref="myInputComponent"
>       :value="myInputValue"
>       @input="myInputValue = $event.target.value"
>       label="Svaret på livet, universet og alt"
>     >
>     </nve-input>
>     <nve-button @click="validate">Sjekk svaret</nve-button>
>   </form>
> </template>
> 
> <script setup lang="ts">
> import { ref } from 'vue';
> import { NveInput, NveButton } from 'nve-designsystem';
> 
> const myInputComponent = ref();
> const myInputValue = ref('');
> 
> const validate = () => {
>   const valid = myInputValue.value == '42';
>   if (!valid) {
>     myInputComponent.value.setCustomValidity('Feil svar');
>   } else {
>     myInputComponent.value.setCustomValidity('');
>   }
> };
> </script>
> ```
> 
> Det er mulig jeg bruker det feil, altså! Det er bra med enkle valideringsmetoder, men jeg synes vi også bør støtte Shoelace sin standard validering så godt det lar seg gjøre.
> 
> Jeg har også en del kommentarer på struktur og særlig dokumentasjon. Har vært litt ekstra pirkete denne gangen, ikke ta det personlig!-)

Det kunne fungere hvis vi lagde en feil melding som viser under input feltet selv i abonner appen. For å få feilmelding under input felte måtte jeg bruke ::after og den tar verdi fra errorMessage som i dette tilfellet er undefined fordi du mangler den. Jeg endret å lese this.validationMessage istedenfor og det fungerer nå. Kan være at vi kan faktisk bruke custom validering på en sånn måte. Ser at man må da også sette sl-blur på nve-input felte for å få onblur validering

2024-01-11 08:43 UTC, gruble commented
Bra! Jeg endret NveInput til å vise this.validationMessage i addErrorMessage() og testet eksemplet ditt i Abonner.
Funka utmerket. Jeg testet også uten submit-knapp i formen, og validering og visning av feilmeldinger funker fortsatt.
Slik jeg forstår det, trenger vi ikke lengre isvalid og errorMessage da for å kjøre våre egne valideringsfunksjoner.

2024-01-11 10:28 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +  @state() isvalidState = true;
jeg må beholde den (bytter navn til alreadyInvalid) fordi jeg klarer ikke å lytte til submit event på den nærmeste formen (vet ikke hvorfor) i nve-input felter, noe som vil hjelpe oss å bestemme om input er valid eller ikke. sl-invalid kastes allerede når data-user-invalid er satt derfor jeg trenger noe state som forteller oss om feltet er allerede invalid eller ikke. 
det å sette state variabel er bedre ytelsesmessig enn å query domen hver gang man gjør noen endringer i input feltet

2024-01-11 11:08 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> + * Da må du sikre å ha med requiredLabel property, og at den har noe verdi
fjernet

2024-01-11 11:09 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +   * Reactive property som brukes for å signere at komponent ikke er valid. Brukes som alternativ til constraint validation. Står som
fjernet

2024-01-11 11:11 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +    this.isvalidState = false;
det man setter selv i applikasjonen (shoelace har ikke det som default, de implementerer det som 'ekstra' i deres eksempel)

2024-01-11 11:12 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +    console.log(this.isvalid);
fjernet

2024-01-11 13:25 UTC, gruble approved these changes
Funka bra.
Jeg har bare noen få kommentarer.
Oppdaterer du beskrivelsen av PR'en så den fortsatt er relevant?
Jeg ser du har skrevet en del om bruk av validering i Readme i en annen PR. 
Vi trenger å ha med et eksempel for Vue. Om det ligger i Readme eller i JsDoc er ikke så nøye, bare det blir med.

2024-01-11 13:25 UTC, gruble commented on src/components/nve-input/nve-input.component.ts
> +  updated(): void {
Siden Shoelace også implementerer updated(), bør du vel kalle super.updated() også?
Kanskje lurt å sende med parametrene også, selv om Shoelace ikke bruker dem i gjeldende versjon?

2024-01-11 13:25 UTC, gruble commented on src/components/nve-input/nve-input.component.ts
> +    if (!this.hasAttribute('data-user-invalid')) {
I denne funksjonen kaller du hasAttribute() to ganger. Blir det kjappere om du gjør det kun en gang?

2024-01-11 13:25 UTC, gruble commented on src/components/nve-input/nve-input.styles.ts
> +  /**fikse til kun user-invalid */
Hva betyr denne kommentaren? Er det noe som må fikses?

2024-01-11 14:41 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +  updated(): void {
hmm jeg ser ikke at sl kaller updated her. kun firstupdate.

2024-01-11 16:42 UTC, amish1188 commented on src/components/nve-input/nve-input.component.ts
> +  updated(): void {
oppdatert

2024-01-12 08:59 UTC, merged