PR: AVN-291 added checkbox group validation
NVE/Designsystem pull request #81
Opened 2024-01-10 08:40 UTC by amish1188

Selv om sjekkboksgruppe er vår egen komponent jeg prøvde å 'etterligne' shoelace validering så at bruker ikke blir forvirret når de ser på komponentene i DOMen. Altså selv om det ikke trengs her, jeg la til samme attributer som shoelace altså data-valid, data-invalid, data-user-valid, data-user-invalid. Sjekkobksgruppe kaster også sl-invalid hvis valideringen feiler. 

Jeg la til alle UU viktige attributer

Testing akkurat på samme måte som input og radio sjekkboks. Man kan teste required (eneaste constraint validering proparty som valideres, akkurat som i radio gruppe) via demo fila, mens isvalid prop burde testes med reaktive apper som vue

2024-01-15 12:07 UTC, gruble requested changes
Ser ut til å virke bra, med unntak av at "*Obligatorisk" er borte. Har en del kommentarer på dokumentasjon og valg av variabelnavn etc. Jeg synes demo-koden kan forenkles og gjøres lettere å forstå.

2024-01-15 12:07 UTC, gruble commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +  /** Disable eller enable gruppa */
Denne kommentaren gir ikke så mye ekstra info, dessuten bruker du engelsk tekst. Hva skjer når man setter disabled til true?

2024-01-15 12:52 UTC, amish1188 commented
> Ser ut til å virke bra, med unntak av at "*Obligatorisk" er borte. Når det value-property: Jeg synes ikke det er teit å ha en array av valgte sjekkbokser (eller mer presist, en array av valgte ledetekster). Litt teit at man bruker ledetekster, kanskje, men jeg tror det er vanlig. Man kunne vurdere heller å ha en boolean[] av alle sjekkboksene, og heller bruke indeks for å finne riktig verdi. Vue får til å binde flere sjekkbokser til samme array, se https://vuejs.org/guide/essentials/forms#checkbox Håper dette vil virke med våre sjekkbokser også! Har ellers en del kommentarer på dokumentasjon og valg av variabelnavn etc. Jeg synes demo-koden kan forenkles og gjøres lettere å forstå. Jeg mener det er viktig at demo-kode er lett å forstå og begrense seg til akkurat det man ønsker å demonstrere.

Det er ikke ledetekster man skal bruke men value fra enkelte sjekkbokser (som vanligvis har samme verdi som selve ledetekst) så det er ikke noe fare, med mindre man har unike values. Lurer på om vi burde da basere 'checked' state på barn sjekkbokser gjennom selectedValues property, og sette true på checked hvis selectedValues inneholder value fra sjekkboksen, eller skal vi ha både values (liste av alle sjekkboksers value), og selectedValues som egentlig viser hvilke sjekkbokser fra values arrayet ble valgt?

2024-01-15 12:54 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.demo.ts
> +      tooltip="Help text"
må være en side effekt fra copy/paste :P

2024-01-15 14:14 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +              <nve-label id="label" value=${this.label} size="small" tooltip=${this.tooltip!}></nve-label>
vi må ha noe type id her så at jeg kan koble aria-labelledby for å følge uu regler. vi kan kalle det hva som helst, men jeg trodde label gir mest mening

2024-01-15 14:15 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +  /** Om noen av sjekkboksene er sjekket inn */
endret

2024-01-17 12:31 UTC, gruble requested changes
Jeg sa ifra om at "*Obligatorisk" ikke vises på forrige runde.
Jeg kan fortsatt ikke se dette noe sted.

2024-01-17 13:36 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.demo.ts
> +  console.log(e.target.checked);
jeg vil ikke logge :P

2024-01-17 13:36 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.demo.ts
jeg fjernet de fordi jeg klarer ikke å vise error state der noe lenger. vi snakket om det

2024-01-17 13:40 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.demo.ts
> +      required
fikset

2024-01-17 13:43 UTC, amish1188 commented on src/utils/updateInvalidProperty.ts
> +  property: boolean,
skrev en eksempel i kommentaren. brukes et par steder

2024-01-18 09:43 UTC, gruble requested changes
Se kommentarer

2024-01-18 09:43 UTC, gruble commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +              <nve-label id="label" value=${this.label} size="small" tooltip=${this.tooltip!}></nve-label>
Det jeg lurte på var om vi kunne risikere at ID'en kommer i konflikt med andre ID'er på samme side. F.eks. hvis du har flere ```<nve-label>``` inni ```<nve-checkbox-group>```

2024-01-18 09:43 UTC, gruble commented on src/components/nve-checkbox/nve-checkbox.demo.ts
Det er noe feil med eksemplet "nve-checkbox-group custom validering"
Feilmeldingen stemmer ikke med det som valideres.
![image](https://github.com/NVE/Designsystem/assets/71138449/f3a96390-6d5e-4fa0-b0fc-0752562a3aaf)
Hvis man velger noe annet en 3 er den fornøyd.

2024-01-18 09:49 UTC, amish1188 commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +              <nve-label id="label" value=${this.label} size="small" tooltip=${this.tooltip!}></nve-label>
Man burde ikke ha flere labels som beskriver en fieldset (hvor aria-label leser fra), det er ikke en god praksis. Forresten det er opp til utviklere hva som de skal skrive i id attribute. Det her er kun en eksempel. Jeg brukte 'label' fordi det er naturlig og fordi jeg trenger ikke å tenkte om den skal kollidere med andre i demo eksempelet.

2024-01-18 10:23 UTC, amish1188 commented on src/components/nve-checkbox/nve-checkbox.demo.ts
Det stemmer. Ser ut at når man brukte required og custom validation, onsubmit handla kun constraint validation og tenkte ikke på custom. Jeg måtte derfor legge til en state variabelen som sjekker om custom validering feiler først. hvis ja skal den ikke fortsette med constraint validation. tror det er ok sånt? ellers må vi fjerne 'required' fra dette eksempelet.

2024-01-18 11:34 UTC, gruble commented on src/components/nve-checkbox-group/nve-checkbox-group.component.ts
> +              <nve-label id="label" value=${this.label} size="small" tooltip=${this.tooltip!}></nve-label>
Jeg tror jeg fikk svar på spørsmålet mitt her:
https://stackoverflow.com/questions/56023322/are-duplicate-ids-allowed-in-separate-shadow-roots

2024-01-18 15:17 UTC, gruble approved these changes
Gratulerer, du kom gjennom nåløyet:-)

2024-01-19 08:16 UTC, merged